INSERT INTO eventos (tipo, nome, data, descricao) VALUES
('SHOW', 'Taylor Swift', '2024-02-15', 'Um evento imperdível para todos os amantes da música pop.'),
('TEATRO', 'A Comédia da Vida', '2024-07-20', 'Uma peça teatral emocionante que retrata com humor momentos complexos da vida. Você não pode perder.'),
('CONCERTO', 'Concerto de Verão', '2024-06-10', 'Um concerto ao ar livre com grandes nomes da música clássica.'),
('PALESTRA', 'Palestra sobre Inteligência Artificial', '2024-09-05', 'Uma palestra informativa sobre as últimas tendências e ferramentas de IA.'),
('WORKSHOP', 'Workshop de Fotografia', '2024-11-30', 'Um workshop prático para aprimorar suas habilidades.'),
('SHOW', 'Stand-up Comedy', '2024-03-18', 'Uma noite de muito riso e diversão com os melhores comediantes do Brasil.'),
('CONCERTO', 'O Fantasma da Ópera', '2024-12-25', 'Uma apresentação clássica de ópera.'),
('TEATRO', 'Festival de Teatro', '2025-04-12', 'Um festival com as melhores peças teatrais do ano.'),
('PALESTRA', 'Fórum de Inovação e Empreendedorismo', '2025-10-08', 'Um fórum que reúne os maiores inovadores do país. Presença dos apresentadores do Shark Tank.'),
('WORKSHOP', 'Aulas de Culinária', '2025-05-20', 'Aulas práticas de culinária com chefs renomados.'),
('SHOW', 'Bruno Mars', '2025-05-22', 'De volta ao Brasil, Bruno promete entregar o maior e melhor show de sua carreira na turnê This is Mars.'),
('TEATRO', 'A Comédia da Vida', '2025-07-14', 'Uma peça teatral emocionante que você não pode perder.'),
('SHOW', 'The Weeknd', '2025-11-02', 'Um show eletrizante ao ar livre com muitos efeitos especiais.'),
('WORKSHOP', 'Café com Ideias', '2025-01-25', 'Um evento que ensina técnicas de brainstorming e priorização para alavancar projetos.');
